const jdBio = `Our team's exceptional resume showcases extensive experience, leadership roles, and quantifiable achievements. Jadon Erwin, our senior developer, has been employed to develop web applications for a variety of large companies, including The Federal Bureau of Investigation (FBI), KBR (an international provider of engineering and technology solutions), and Sinch, a provider whose technology powers Airbnb, What'sApp, Uber, and other well-known brands.

He holds a university degree in Physics and Computer Science, and he began his career developing quantum computing algorithms for national security defense contractors in Washington D.C. before beginning employment at FBI headquarters in Quantico. He currently specializes in web development using AI and integrating bots similar to ChatGPT into various applications.

Jadon’s impressive skills are best-suited for web applications extending beyond a simple landing page; for example, Jadon prefers complex applications requiring challenging moving parts. His wide range of technical experience has made him a professional-problem-solver, and his advanced abilities are the perfect fit for delivering high-end website development products.`

const laraeBio = `In addition to web development, we value streamlined work flows and organized project management. Our CEO, LaRae Day, is an experienced company  and technical project manager with a diverse background in managing web development projects and IT teams, specifically projects involving web applications. She specializes in supporting development teams in creating a positive user experience, always keeping the customer and target audience in mind.

Her competitive expertise in public relations and digital marketing is an asset in the final quality assurance of your digital delivery. She has worked professionally on digital deliverables and virtual campaigns with many well-known brands, including Disney, Hallmark, Marvel Studios, Prada Milano, Ralph Lauren, Victoria's Secret, Sephora, and other household names in the luxury space. Her work has taken her to New York Fashion Week, Paris Fashion Week, The 66th Annual Grammy Awards, National Amazon convention for upper-management, corporate Washington D.C, the official French Embassy in D.C, and more.  She has recently been featured in Yahoo Finance for her work in digital media.`

export {jdBio, laraeBio}